print("")
print("Exercise 4 - Day001 The Final project")
print("Welcome to Band Name Generator")
name4 = input("What city did you grow up in?")
pet_name = input(" What's your pet name?")
print("Your Band Name is", name4, pet_name)